export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START'; 
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS'; 
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE'; 

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const CREATE_LIKE_REQUEST = 'CREATE_LIKE_REQUEST'
export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS'
export const CREATE_LIKE_FAILURE = 'CREATE_LIKE_FAILURE'
export const REMOVE_LIKE_REQUEST = 'REMOVE_LIKE_REQUEST'
export const REMOVE_LIKE_SUCCESS = 'REMOVE_LIKE_SUCCESS'
export const REMOVE_LIKE_FAILURE = 'REMOVE_LIKE_FAILURE'